version: '2'

services:
  web-frontend:
    build:
      context: .
      dockerfile: ./docker/frontend
    ports:
      - 80
    depends_on:
      - web-backend


  web-backend:
    build:
      context: .
      dockerfile: ./docker/backend